# Lab 10.01 : Convolutional layer - demo

In [0]:
import torch
import torch.nn as nn

### Make a convolutional module
* inputs:  2 channels
* output:  5 activation maps 
* filters are 3x3
* padding with one layer of zero to not shrink anything

In [0]:
mod = nn.Conv2d(2 ,5 ,kernel_size=3, padding=1)

### Make an input 2 x 6 x 6  (two channels, each one has 6 x 6 pixels )

In [3]:
bs=1

x=torch.rand(bs,2,6,6)

print(x)

tensor([[[[3.8924e-01, 2.8111e-01, 3.9458e-01, 5.4472e-01, 8.9896e-01,
           6.7415e-01],
          [1.2609e-01, 4.2187e-01, 9.7422e-01, 8.8614e-01, 6.5464e-01,
           6.2373e-01],
          [6.4031e-01, 5.9480e-01, 1.3563e-01, 6.3239e-01, 9.3274e-02,
           7.8706e-01],
          [8.5736e-01, 9.6733e-01, 9.2011e-01, 2.1499e-01, 5.8989e-01,
           3.4720e-01],
          [7.2778e-01, 4.3603e-01, 8.2201e-01, 5.7710e-01, 9.8754e-02,
           6.1736e-01],
          [6.3118e-01, 5.8050e-01, 3.3735e-01, 2.7686e-04, 8.6392e-01,
           4.8263e-01]],

         [[8.9739e-01, 3.1603e-01, 7.6371e-02, 2.4924e-01, 9.1510e-01,
           5.0616e-01],
          [8.4872e-01, 7.9394e-01, 1.4105e-01, 6.8873e-01, 6.3710e-01,
           3.8950e-01],
          [1.8501e-01, 8.7230e-01, 8.8820e-01, 2.6814e-01, 2.8737e-01,
           5.2325e-02],
          [7.9564e-01, 1.9024e-01, 2.4261e-01, 8.8089e-01, 9.2581e-01,
           1.5459e-01],
          [7.1314e-02, 9.5308e-01, 9.2306e-01, 2

### Feed it to the convolutional layer: the output should have 5 channels (each one is 6x6)

In [4]:
y=mod(x)

print(y)

tensor([[[[ 2.4434e-01, -2.1455e-01, -1.1434e-01,  2.1102e-01, -1.1876e-01,
           -2.6857e-01],
          [ 2.2203e-01,  2.2601e-01, -1.1096e-01, -7.8580e-03, -1.0282e-01,
            1.2256e-01],
          [ 1.0970e-01, -1.6916e-01,  9.2003e-02,  7.9968e-02,  3.2426e-01,
           -8.4991e-02],
          [ 2.5172e-02,  2.4334e-01,  1.9558e-01,  2.1306e-01, -2.0255e-01,
            4.9346e-02],
          [ 2.4678e-01,  3.7970e-01, -2.1638e-01, -1.1856e-01,  5.2583e-01,
            8.2455e-02],
          [ 1.4630e-02, -8.5480e-02,  2.5068e-02,  4.0648e-01,  3.8560e-05,
            3.0683e-02]],

         [[-2.6778e-02,  1.4190e-01,  1.0702e-01,  2.1868e-01,  1.3799e-01,
            4.1649e-02],
          [ 2.0403e-01, -9.2785e-02, -3.5008e-02, -3.0897e-02,  1.4660e-01,
            7.2192e-02],
          [ 2.7742e-01,  6.8287e-02,  5.8546e-03, -1.5055e-01, -3.6788e-02,
           -1.0012e-01],
          [ 4.2861e-02,  2.8326e-02, -9.1246e-02,  1.3271e-01, -1.4792e-01,
            1

### Lets look at the 5 filters.
* Our filters are 2x3x3
* Each of the filter has 2 channels because the inputs have two channels

In [5]:
mod.weight

Parameter containing:
tensor([[[[ 0.1375,  0.0881, -0.1370],
          [ 0.1396, -0.1729,  0.0755],
          [-0.1037,  0.0156, -0.1461]],

         [[ 0.1200,  0.0343, -0.0251],
          [-0.2240, -0.0796,  0.1166],
          [-0.1507,  0.2332,  0.1960]]],


        [[[-0.0232,  0.1156, -0.1960],
          [-0.0158, -0.0921,  0.0999],
          [-0.0140,  0.1672,  0.1212]],

         [[-0.1075,  0.0177,  0.0101],
          [ 0.0611,  0.0882,  0.1438],
          [-0.0903, -0.0444, -0.2206]]],


        [[[-0.0330,  0.0741,  0.1223],
          [ 0.1567, -0.1970,  0.2317],
          [-0.2339,  0.1121, -0.0136]],

         [[-0.1255,  0.0167, -0.2245],
          [-0.0424, -0.0757, -0.1447],
          [ 0.1772, -0.2248, -0.1246]]],


        [[[ 0.0791,  0.0470,  0.1600],
          [ 0.2322, -0.0444, -0.0953],
          [ 0.0797,  0.1071,  0.0664]],

         [[ 0.0653, -0.0407,  0.1433],
          [-0.0426, -0.1531,  0.0233],
          [-0.1663,  0.2026,  0.2147]]],


        [[[ 0.0659