# Introduction to PyTorch  

In [0]:
import torch

## Code examples

### Construct a vector of 3 elements

In [0]:
x=torch.Tensor( [5.3 , 2.1 , -3.1 ] )
print(x)

tensor([ 5.3000,  2.1000, -3.1000])


### Construct a  2 x 2 matrix

In [0]:
A=torch.Tensor( [ [5.3,2.1] , [0.2,2.1] ] )
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


### Construct a random 10 x 2 matrix

In [0]:
A=torch.rand(10,2)
print(A)

tensor([[0.0433, 0.1681],
        [0.2373, 0.2254],
        [0.6232, 0.2286],
        [0.3954, 0.7913],
        [0.6602, 0.7088],
        [0.6103, 0.6614],
        [0.8230, 0.4297],
        [0.1095, 0.0751],
        [0.3767, 0.6192],
        [0.1892, 0.6318]])


### Construct a 10 x 2 matrix filled with zeros

In [0]:
A=torch.zeros(10,2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### Construct a 5 x 2 x 2 random Tensor 

In [0]:
B = torch.rand(5,2,2)
print(B)

tensor([[[0.3624, 0.1650],
         [0.5240, 0.8883]],

        [[0.5155, 0.2018],
         [0.1918, 0.7649]],

        [[0.1081, 0.2063],
         [0.7260, 0.3426]],

        [[0.7217, 0.5846],
         [0.8919, 0.7750]],

        [[0.6260, 0.6378],
         [0.1892, 0.7977]]])


In [0]:
B.size()

torch.Size([5, 2, 2])

In [0]:
B.dim()

3

### Size and Dimension of a Tensor 

#### A 3-dimensional Tensor 

In [0]:
A=torch.rand(3,2,2)
print(A)

tensor([[[0.8826, 0.2284],
         [0.7530, 0.2435]],

        [[0.2213, 0.6198],
         [0.8820, 0.9255]],

        [[0.5898, 0.3268],
         [0.3918, 0.9752]]])


In [0]:
print(  A.dim()   )

3


In [0]:
print(  A.size()   )

torch.Size([3, 2, 2])


In [0]:
print(  A.size(0)  )

3


#### A 2-dimensional Tensor 

In [0]:
B=torch.rand(3,5)
print(B)

tensor([[0.7671, 0.6470, 0.7702, 0.6315, 0.4696],
        [0.7422, 0.5464, 0.1165, 0.6252, 0.5320],
        [0.9052, 0.0902, 0.5475, 0.0883, 0.6006]])


In [0]:
print( B.dim()  )

2


In [0]:
print( B.size()  )

torch.Size([3, 5])


In [0]:
print( B.size(0) )

3


In [0]:
print( B.size(1) )

5


#### A 1-dimensional Tensor

In [0]:
x=torch.rand(7)
print(x)

tensor([0.8747, 0.9436, 0.9673, 0.3596, 0.0489, 0.9237, 0.5866])


In [0]:
print( x.dim() )

1


In [0]:
print( x.size() )

torch.Size([7])


### Adding and multiplying tensors

In [0]:
A=torch.rand(2,2)
B=torch.rand(2,2)

C=2*B
D=A+C
E=A*B

print(A)
print('')
print(B)
print('')
print(C)
print('')
print(C)
print('')
print(E)

tensor([[0.7513, 0.6579],
        [0.6255, 0.2182]])

tensor([[0.4870, 0.2859],
        [0.7319, 0.6777]])

tensor([[0.9740, 0.5718],
        [1.4638, 1.3553]])

tensor([[0.9740, 0.5718],
        [1.4638, 1.3553]])

tensor([[0.3659, 0.1881],
        [0.4578, 0.1479]])


### Floats versus integers

In [0]:
x=torch.Tensor([1.2 , 2.5])
print(x)
print(x.type())

tensor([1.2000, 2.5000])
torch.FloatTensor


In [0]:
y=torch.LongTensor([5,6])
print(y)
print(y.type())

tensor([5, 6])
torch.LongTensor


In [0]:
y=y.float()
print(y)
print(y.type())

tensor([5., 6.])
torch.FloatTensor


In [0]:
x=x.long()
print(x)
print(x.type())

tensor([1, 2])
torch.LongTensor


### Other functions

In [0]:
x=torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [0]:
x=torch.randperm(10)
print(x)
print(x.type())

tensor([5, 1, 7, 6, 0, 9, 3, 4, 8, 2])
torch.LongTensor


In [0]:
x=torch.arange(10).long()
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


### Tips

Check tensor sizes for algebra computations like multiplication torch.mm(X1,X2) with X1.size(), X2.size()

Check tensor type for data manipulations with X.type()

### Reshaping a tensor

In [0]:
x=torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [0]:
print( x.view(2,5) )

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [0]:
print( x.view(5,2) )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Note that the original tensor x was NOT modified

In [0]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### To make the change permanent you need to create a new tensor

In [0]:
y=x.view(5,2)

print(x)
print('')
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Slicing a tensor

In [0]:
print( y )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [0]:
print( y[0] )

tensor([0, 1])


In [0]:
print( y[1] )

tensor([2, 3])


In [0]:
v = y[2]
print(v)

tensor([4, 5])


### Extract row 1 (included) to row 4 (excluded)

In [0]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [0]:
print( y[1:4] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


In [0]:
idx = 1
n=3

print( y[idx:idx+n] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


### Let check the sizes after slicing

In [0]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [0]:
z= y[1:1+3]
print(z)

print('')

print('dimension=',z.dim())
print(z.size())

tensor([[2, 3],
        [4, 5],
        [6, 7]])

dimension= 2
torch.Size([3, 2])


In [0]:
v=y[1]
print(v)

print('')


print('dimension=',v.dim())
print(v.size())

tensor([2, 3])

dimension= 1
torch.Size([2])


### Acessing the entries of a Tensor

In [0]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [0]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [0]:
a=y[4,0]
print(a) # a is a scalar, not a tensor

tensor(8)


In [0]:
print(a.dim())
print(a.size())

0
torch.Size([])


### A matrix is 2-dimensional Tensor
### A row of a matrix is a 1-dimensional Tensor
### An entry of a matrix is a 0-dimensional  Tensor

### 0-dimensional Tensor are scalar!

### If we want to convert a 0-dimensional Tensor into  python number, we need to use item()

In [0]:
b=a.item()
print(a)
print(type(a))
print(b)
print(type(b))

tensor(8)
<class 'torch.Tensor'>
8
<class 'int'>


## Exercises

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [0]:
# Write your code here

### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [0]:
# Write your code here

### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [0]:
# Write your code here

### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [0]:
# Write your code here

### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [0]:
# Write your code here